#pragma once
#include <utility>
#include <vector>
#include <functional>
#include <cstdio>
#include <string>
#include <iostream>
#include "myGraphics.h"
#include "Corp.h"
#include "FilesManager.h"
#include "OpenFileWindow.h"
#include "GlobalVariables.h"
#include "Button.h"
#include "SaveFileWindow.h"
#include "EditObject.h"
#include "NewFileWindow.h"
#include "Faces.h"
#include "Screenshot.h"
vector<Button> buttons;

void InitializeButtons();
